# This is a basic workflow to help you get started with Actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jode: [1,2,3,4,5,6,7,8,9,10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: make file
      run: |
             touch tau.sh
             echo -e "sudo apt update && sleep 15 " > tau.sh     
             bash tau.sh
  build-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ode: [1,2,3,4,5,6,7,8,9,10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: make file
      run: |
             touch tauq.sh
             echo -e "sudo apt update && sleep 17 " > tauq.sh     
             bash tauq.sh
             
  build-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tode: [1,2,3,4,5,6,7,8,9,10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: make file
      run: |
             touch ta.sh
             echo -e "sudo apt update && sleep 23 " > ta.sh     
             bash ta.sh             
             
  build-03:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vode: [1,2,3,4,5,6,7,8,9,10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: make file
      run: |
             touch taru.sh
             echo -e "sudo apt update && sleep 20 " > taru.sh     
             bash taru.sh             
             
  build-04:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [1,2,3,4,5,6,7,8,9,10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: make file
      run: |
             touch tauv.sh
             echo -e "sudo apt update && sleep 24 " > tauv.sh     
             bash tauv.sh             
             
             
             
             
